
default: &default
  adapter: postgresql
  host: <%= ENV["DATABASE_HOST"] %>
  username: <%= ENV["DATABASE_USER"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %> 
  encoding: utf8
  min_messages: warning
  pool: 2
  timeout: 5000


development:
  <<: *default
  database: tweeets_development


test:
  <<: *default
  database: tweeets_test


production:
  <<: *default
  database: tweeets_production